#Docker compose for Drupal & Postgres
version: '2'

services:

 drupal:
  image: drupal
  ports:
   - '8080:80'

 postgres:
  image: postgres
  environment:
  #you can use your own password in this variable
   - POSTGRES_PASSWORD=samedrupal
  volumes:
   - drupaldb:/var/lib/postgresql/data
##  volume_driver: dvol

volumes:
 drupaldb:
##  external: true
